CREATE DATABASE IF NOT EXISTS Autolavado;

USE Autolavado;

CREATE TABLE Cliente (
ID_CLIENTE INT NOT NULL UNIQUE AUTO_INCREMENT PRIMARY KEY,
NOMBRE_CLIENTE VARCHAR(50) NOT NULL,
APELLIDO_CLIENTE VARCHAR(50) NOT NULL,
DIRECCION_CLIENTE VARCHAR(50),
TELEFONO_CLIENTE INT(12) NOT NULL UNIQUE
);

CREATE TABLE Tipo_Auto(
ID_TIPO INT NOT NULL UNIQUE,
DESCRIPCION_TIPO VARCHAR(20) NOT NULL
);

CREATE TABLE Auto(
ID_AUTO INT NOT NULL UNIQUE AUTO_INCREMENT PRIMARY KEY,
PLACA_AUTO VARCHAR(6) NOT NULL UNIQUE,
ID_CLIENTE INT NOT NULL,
ID_TIPO INT NOT NULL,
FOREIGN KEY (ID_CLIENTE)
   REFERENCES Cliente(ID_CLIENTE)
   ON DELETE CASCADE
   ON UPDATE CASCADE,
FOREIGN KEY (ID_TIPO)
   REFERENCES Tipo_Auto(ID_TIPO)
   ON DELETE CASCADE
   ON UPDATE CASCADE
);

CREATE TABLE Empleado(
ID_EMPLEADO INT NOT NULL UNIQUE AUTO_INCREMENT PRIMARY KEY,
NOMBRE_EMPLEADO VARCHAR(50) NOT NULL,
APELLIDO_EMPLEADO VARCHAR(50) NOT NULL,
FUNCION_EMPLEADO VARCHAR(50) NOT NULL,
SUELDO_EMPLEADO DECIMAL(5,2) NOT NULL
);

CREATE TABLE Horario(
  ID_HORARIO INT NOT NULL UNIQUE AUTO_INCREMENT PRIMARY KEY,
  ID_EMPLEADO INT NOT NULL,
  HORA_ENTRADA TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  HORA_SALIDA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY(ID_EMPLEADO)
    REFERENCES Empleado(ID_EMPLEADO)
    ON DELETE CASCADE 
    ON UPDATE CASCADE
);

CREATE TABLE Proveedor(
  ID_PROVEEDOR INT NOT NULL UNIQUE AUTO_INCREMENT PRIMARY KEY,
  NOMBRE_PROVEEDOR VARCHAR(50) NOT NULL UNIQUE,
  DIRECCION_PROVEEDOR VARCHAR(50) NOT NULL,
  TELEFONO_PROVEEDOR INT(12) NOT NULL UNIQUE
  );

CREATE TABLE Producto(
ID_PRODUCTO INT NOT NULL UNIQUE AUTO_INCREMENT PRIMARY KEY,
ID_PROVEEDOR INT NOT NULL,
NOMBRE_PRODUCTO VARCHAR(50) NOT NULL,
CANTIDAD_PRODUCTO INT NOT NULL,
PRECIO_PRODUCTO DECIMAL(5,2) NOT NULL,
FOREIGN KEY(ID_PRODUCTO)
  REFERENCES Producto(ID_PRODUCTO)
  ON DELETE CASCADE
  ON UPDATE CASCADE
  );

CREATE TABLE Servicio(
ID_SERVICIO INT NOT NULL UNIQUE AUTO_INCREMENT PRIMARY KEY,
ID_TIPO INT NOT NULL,
ID_PRODUCTO INT NOT NULL,
DESCRIPCION_SERVICIO VARCHAR(50),
COSTO_SERVICIO DECIMAL(4,2) NOT NULL,
PRECIO_TOTAL DECIMAL(4,2) NOT NULL,
FOREIGN KEY(ID_TIPO)
  REFERENCES Tipo_Auto(ID_TIPO)
  ON DELETE CASCADE
  ON UPDATE CASCADE,
FOREIGN KEY(ID_PRODUCTO)
  REFERENCES Producto(ID_PRODUCTO)
  ON DELETE CASCADE 
  ON UPDATE CASCADE
);

CREATE TABLE Venta(
ID_VENTA INT NOT NULL UNIQUE AUTO_INCREMENT PRIMARY KEY,
ID_AUTO INT NOT NULL,
ID_SERVICIO INT NOT NULL,
ID_EMPLEADO INT NOT NULL,
FOREIGN KEY(ID_AUTO)
  REFERENCES Auto(ID_AUTO)
  ON DELETE CASCADE
  ON UPDATE CASCADE
);

DROP TABLE servicio;
DROP TABLE empleado;
DROP TABLE horario;
DROP TABLE producto;
DROP TABLE venta;


